schema: 'apollo/**/*.graphqls'
schemaEntrypoint: 'apollo/schema.graphqls'
documents: '**/*.graphql'
plugins:
  - typescript
  - typescript-operations
  - typescript-react-apollo
config:
  dedupeOperationSuffix: true
  addOperationExport: true
cacheDir: __generated__
