schema: 'services/**/*.graphqls'
schemaEntrypoint: 'services/schema.graphqls'
documents: '**/*.graphql'
plugins:
  - typescript
  - typescript-operations
  - typescript-react-apollo
config:
  dedupeOperationSuffix: true
  addOperationExport: true
cacheDir: .generated
